### ISSUE TITLE
Default password

### ISSUE THREAD

**Issue by IanMoroney** [kubevirt/containerdisks#228]
**What happened**:
I'm trying to log into a VM created from quay.io/containerdisks/ubuntu:24.04 using the default username `ubuntu` but I don't know what the default password is.
I tried using cloudInitNoCloud to set both a user with a password, and to set a password on its own, but neither have worked.
At the moment i'm not using bridge networking, so I don't have the ability to ssh into the guest, and `virtctl ssh` returns a "connection refused", so assigning the ssh_authorized_keys doesn't help me.
from `virtctl vnc`, i can see the guest is running and is at the login screen, i just can't get in.

**What you expected to happen**:
Trying to log into the machine

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 1.4.0
- Kubernetes version (use `kubectl version`): 1.3.0
- VM or VMI specifications: N/A
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-template
  namespace: kvrunner
spec:
  runStrategy: Manual
  template:
    metadata:
      name: runner
    spec:
      architecture: amd64
      terminationGracePeriodSeconds: 30
      domain:
        devices:
          filesystems:
            - name: runner-info
              virtiofs: {}
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        cpu:
          cores: 3
        resources:
          requests:
            memory: 14Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:24.04
        # - name: runner-info
        #   configMap:
        #     name: runner-info-configmap
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: ubuntu
              users:
                - name: runner
                  password: runner
                  homedir: /home/runner
                  sudo: ["ALL=(ALL) NOPASSWD:ALL"]
              mounts:
                - [ runner-info, /runner-info/, virtiofs, "rw,relatime,user=ubuntu" ]
              packages:
                - jq
              bootcmd:
                - "sudo mkdir /opt/runner"
                - "curl -sL https://github.com/actions/runner/releases/download/v2.320.0/actions-runner-linux-x64-2.320.0.tar.gz | sudo tar -xz -C /opt/runner"
                - "sudo /opt/runner/bin/installdependencies.sh"
              runcmd:
                - "sudo chown -R runner: /opt/runner"
                - "sudo runuser -l runner -c '/opt/runner/run.sh --jitconfig $(jq -r '.jitconfig' /runner-info/runner-info.json)'"
                - "sudo poweroff"
```
